# true = change biomes server side (affects selected worlds, remember to take a backup of them)
# false = change biomes client side (affects all worlds, biomes will revert back to normal when the plugin is removed)
legacy: false

# (for legacy mode only)
# 0 = snow
# 1 = set biome to plains
mode: 0

# list of worlds where snowing is enabled
worlds:
  - "world"
